[package]
name = "elegance"
version = "0.3.2"
edition = "2021"
description = "A pretty-printing library for Rust with a focus on speed and compactness."
license = "Apache-2.0"
rust-version = "1.78"
repository = "https://github.com/Wybxc/elegance"
categories = ["command-line-interface", "development-tools"]
keywords = ["printing", "pretty-printing", "console"]

[dependencies]
unicode-width = { version = "0.2.0", optional = true }

[features]
default = ["unicode-width"]
unicode-width = ["dep:unicode-width"]

[dev-dependencies]
criterion = "0.7.0"
indoc = "2.0.5"
serde_json = "1.0.121"

[[bench]]
name = "json"
harness = false
